#include <iostream>
using namespace std;

int main(){
    //Print multiplication table of 6 using for loop:
    //for(int i=1; i<=10; i++){
    //    cout<<i*6<<endl;
    //}   

    //Print multiplication table of 4 using while loop:
    //int i=1;
    //while(i<=10){
    //    cout<<i*4<<endl;
    //   i++;
    // }

    //Print multiplication table of 13 using do-while loop:
    int i=1;
    do{
        cout<<i*13<<endl;
        i++;
    }while(i<=10);

return 0;
}